### ISSUE TITLE
Deploy issue

### ISSUE THREAD

**Issue by killshotSierra** [XiaomiFirmwareUpdater/xiaomi_uranus_chatbot#119]
Hello ı filled all config envs (for telegram bot) but when try to start its giving error  
what should ı do ?

![Screenshot_20230227-121109_Termius](https://user-images.githubusercontent.com/97761336/221521708-b6f07445-5df3-4c05-99cc-c94ce4e94976.png)

**Comment by yshalsager** [comment]
fixed, please pull latest changes @killshotSierra

**Comment by killshotSierra** [comment]
I pulled changes and re tried but got another error 

![Screenshot_20230228-075310_Termius~2](https://user-images.githubusercontent.com/97761336/221757873-0a11421a-d7fe-4c74-95f6-0f8e7394c663.png)

**Comment by yshalsager** [comment]
@killshotSierra make sure you have installed the dependencies

**Comment by killshotSierra** [comment]
> @killshotSierra make sure you have installed the dependencies

İ installed aiohttp and Telethon for telegram bot

**Comment by yshalsager** [comment]
@killshotSierra run `pip install .` to install all required dependencies

**Comment by killshotSierra** [comment]
Done but but ı have this error now 
![Screenshot_20230228-110920_Termius](https://user-images.githubusercontent.com/97761336/221792263-5655bbe3-b3f8-44a4-8e1c-ea2d27b490a3.png)
