### ISSUE TITLE
Typo in i18n/zh-CN

### ISSUE THREAD

**Issue by knano** [XiaomiFirmwareUpdater/xiaomi_uranus_chatbot#15]
Hi. I find several mentions of `codenames_name[device]` in https://github.com/XiaomiFirmwareUpdater/xiaomi_uranus_chatbot/blob/2b5f4a1de09dbf6b9ca567d4bbcb48217c739b0c/uranus_bot/i18n/zh-CN.yml (line 13,48,70,72,126). It looks like that they might be `codenames_names[device]` instead of `codenames_name[device]`?

Thanks!

**Comment by yshalsager** [comment]
Hi
Thanks for opening this issue.

Well, codenames_names is an internal variable for the bot which has codenames of devices mapped to their names, so it's not a typo :)

In case you would like to contribute to the current translation and refine it feel free to do so using crowdin link in the project readme.

Regards

**Comment by knano** [comment]
@yshalsager Sorry, didn't express it clearly. I mean that the variable name should be codenames_name**s** but not codenames_name. 
For example, now I got this when I use `@XiaomiGeeksBot`:
![image](https://user-images.githubusercontent.com/64005121/117814541-0514ff00-b297-11eb-85cb-747adbd68620.png)
The right variable name is not right so it does not replace the placeholder correctly.

**Comment by yshalsager** [comment]
> @yshalsager Sorry, I didn't express it clearly. I mean that the variable name should be codenames_name**s** but not codenames_name.
> 
Oh, I fixed it now, Thanks for reporting!
